version: '3'

services:
  api:
    container_name: epanel_api
    image: epanel/api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: epanel
      DATABASE_PASSWORD: epanel123
      DATABASE_NAME: epanel
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: epanel_db
    image: epanel/database:latest
    ports:
      - '5432:5432'
